### ISSUE TITLE
Cant access some datasets on ERDDAP

### ISSUE THREAD

**Issue by abfleishman** [rmendels/xtractomatic#1]
I am trying to access some of the sea surface height datasets listed on the ERDDAP website and I am having issues.  Specifically, I am interested in hycom_GLBa008_tyx from 2012-2016.
When I run `searchData(searchList = list(list("varname","ssh")))` it only lists two datasets both of which are from the coastwatch interface.  
On ERDDAP there are 25 SSH datasets and none are listed through searchData.  Am I doing something wrong?
```
xtracto(xpos=temp$Longitude,
             ypos=temp$Latitude,
             tpos=temp$date,
             dtype="hycom_GLBa008_tyx",
             xlen=0.1, 
             ylen=0.1, 
             verbose=TRUE)
```

**Comment by rmendels** [comment]
HI Abram:

You have done exactly right.  xtractomatic only accesses some of the datasets on ERDDAP.  This was by design.  We included what we thought were the most important datasets, so people do not get overwhelmed with the different SSTs, chlorophylls etc.

You have two options.  If you just want data in a bounding box,  use the wonderful rerddap package that is available from CRAN.  If you are trying to do an extract along a track,  and are willing to live dangerously, I have package still under development,  but will work with any gridded dataset on any ERDDAP, see:

https://github.com/rmendels/rerddapXtracto

Thanks,

-Roy

> On Jan 18, 2017, at 9:06 AM, Abram Fleishman <notifications@github.com> wrote:
> 
> I am trying to access some of the sea surface height datasets listed on the ERDDAP website and I am having issues. Specifically, I am interested in hycom_GLBa008_tyx from 2012-2016.
> When I run searchData(searchList = list(list("varname","ssh"))) it only lists two datasets both of which are from the coastwatch interface.
> On ERDDAP there are 25 SSH datasets and none are listed through searchData. Am I doing something wrong?
> 
> xtracto(xpos=temp$Longitude,
>              ypos=temp$Latitude,
>              tpos=temp$date,
>              dtype="hycom_GLBa008_tyx",
>              xlen=0.1, 
>              ylen=0.1, 
>              verbose=TRUE)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by abfleishman** [comment]
Thanks for your speedy reply (and your awesome package)!  We are trying to extract data along tracks so maybe we will try living dangerously and use your new package.

**Comment by rmendels** [comment]
let me know if you have  problems with it.  If you are interested,  you can view the vignette for the package at:

https://rmendels.github.io/UsingrerddapXtracto.nb.html

It gives a pretty good idea of how to use it.  If you do run into problems let me know.  I am in the midst of refactoring the code some,  not changing any functionality,  just making it easier for someone else to look at and provide comments.

-Roy

> On Jan 18, 2017, at 9:30 AM, Abram Fleishman <notifications@github.com> wrote:
> 
> Thanks for your speedy reply (and your awesome package)! We are trying to extract data along tracks so maybe we will try living dangerously and use your new package.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.
